### ISSUE TITLE
Wrong FOV causes fisheye effect

### ISSUE THREAD

**Issue by Midnightmaster** [DrBeef/QuakeQuest#5]
Could it be that the FOV is not quite right? I have a light fisheye effect.

**Comment by DrBeef** [comment]
Hopefully latest release should resolve this issue, please see V1.1.0 release notes, can you confirm if it is better please.

You will need to also delete commandline.txt from the QuakeQuest folder in order for the supersampling to be active when you next run it.

**Comment by Midnightmaster** [comment]
Yeah, it's better now, but the picture still keeps moving when you turn your head. We are almost there. Shouldn't the result be the same for every quest user? So if I still have a little fisheye effect, it should be the same for everyone, right? Nevertheless thanks first of all. A real achievement in such a short time to get the whole thing running on the Quest with 6dof. BTW: Would be really cool if we could switch on the RT World option sometime without framedrops. But the quest is probably too slow for that...

**Comment by Midnightmaster** [comment]
I think fov 110 is quite ok (was 112 before). I added this line to id1\config.cfg: "fov" "110".

**Comment by terreb** [comment]
Thank you @DrBeef, with the 1.1.0 version it's noticeable better for me! When I turn my head left/right horizontally I don't notice fisheye effect anymore (like @Midnightmaster suggested I also added fov 110 to the config file though). However when I look up and turn my head left/right I still notice it. Could it also has to do with aspect ration?

**Comment by QUAKEULUS** [comment]
is this related to the Known Issue:  "Orientation when headset looking near poles (north or south) doesn't work very well at all (Quaternion to Euler Angle issue) - if anyone knows what's going on there I'd appreciate some help!, it was like this on the GearVR and not many people complained about it, but it bothers me" ?

**Comment by DrBeef** [comment]
Yes, this outstanding issue is related to the "Quaternion to Euler Angle issue", I'm going to close this issue and create a new one for that.
